server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://mysql:3307/dockerDB?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hak
    password: hak

mybatis:
  type-aliases-package:
  mapper-locations: /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true